//player constants
var MAX_ENERGY = 100;
var ENERGY_ATTACK = 100;
var ENERGY_INCREMENT = 20;
var IDLE_ENERGY_MULTIPLIER = 0.001;
var HEALTH = 100;
var BLOCKED_DAMAGE_MULTIPLIER = 0.05;
var BLOCKED_DAMAGE_ENERGY_MULTIPLIER = 0.1;
var ENERGY_INCREMENT_ON_HIT = 1.2;
var BLOCKED_ATTACK_KICKBACK = 0.35;
var ATTACK_KICKBACK = 0.5;
var MAX_MOVE_SPEED = 4;

//constants for stickman's damages
var STICKMAN_PUNCH1_DAMAGE = 10;
var STICKMAN_PUNCH2_DAMAGE = 10;
var STICKMAN_PUNCH3_DAMAGE = 10;
var STICKMAN_KICK1_DAMAGE = 10;
var STICKMAN_KICK2_DAMAGE = 10;
var STICKMAN_KICK3_DAMAGE = 10;
var STICKMAN_JUMPKICK_DAMAGE = 10;
var STICKMAN_SPECIAL_DAMAGE = 30;

//constants for jenkins's damages
var JENKINS_PUNCH1_DAMAGE = 10;
var JENKINS_PUNCH2_DAMAGE = 10;
var JENKINS_PUNCH3_DAMAGE = 10;
var JENKINS_KICK1_DAMAGE = 10;
var JENKINS_KICK2_DAMAGE = 10;
var JENKINS_KICK3_DAMAGE = 10;
var JENKINS_JUMPKICK_DAMAGE = 10;
var JENKINS_SPECIAL_DAMAGE = 7.5;

//constants for ephie's damages
var EPHIE_PUNCH1_DAMAGE = 10;
var EPHIE_PUNCH2_DAMAGE = 10;
var EPHIE_PUNCH3_DAMAGE = 10;
var EPHIE_KICK1_DAMAGE = 10;
var EPHIE_KICK2_DAMAGE = 10;
var EPHIE_KICK3_DAMAGE = 10;
var EPHIE_JUMPKICK_DAMAGE = 10;
var EPHIE_SPECIAL_DAMAGE = 10;

//constants for samuru's damages
var SAMURU_PUNCH1_DAMAGE = 10;
var SAMURU_PUNCH2_DAMAGE = 10;
var SAMURU_PUNCH3_DAMAGE = 10;
var SAMURU_KICK1_DAMAGE = 10;
var SAMURU_KICK2_DAMAGE = 10;
var SAMURU_KICK3_DAMAGE = 10;
var SAMURU_JUMPKICK_DAMAGE = 10;
var SAMURU_SPECIAL_DAMAGE = 30;

//constants for ai
var AI_ATTACK_LENGTH = 50;
var	AI_FLEE_LENGTH = 70;
var AI_MOVE_TIME = 1;

//constants for animations
var FRAME_WIDTH = 215;
var FRAME_HEIGHT = 215;
var FRAME_DURATION = 0.1;
var SPRITESHEET_WIDTH = 1500;
var SCALE = 1;

//constants for environment
var WIDTH = 800;
var HEIGHT = 600;
var GROUND = 0;
var AM = new AssetManager();
